title: Ying Wang's Homepage
page-top-title: Ying Wang
# top-section-bg-text: May you be faithful to yourself, live earnestly and laugh freely.
home-subtitle: Ying Wang&ensp;|&ensp;王莹
copyright-text: '&copy; Ying Wang 2023-2025. All Rights Reserved.'
